@baseUrl = http://localhost:8000
@productId = PRD#1
@userId = user123


### View the cart for a specific user

GET {{baseUrl}}/cart/{{userId}} HTTP/1.1

### Add a product to the cart

# Make sure to replace YOUR_PRODUCT_ID_HERE with a real ID from the /products endpoint
POST {{baseUrl}}/cart/{{userId}} HTTP/1.1
Content-Type: application/json

{
  "productId": "{{productId}}",
  "quantity": 1
}

### Update a product's quantity in the cart

# Make sure to replace YOUR_PRODUCT_ID_HERE with a real ID that is already in the cart
PUT {{baseUrl}}/cart/{{userId}}/{{productId}} HTTP/1.1
Content-Type: application/json

{
  "quantity": 3
}

### Remove a product from the cart

# Make sure to replace YOUR_PRODUCT_ID_HERE with a real ID that is already in the cart
DELETE {{baseUrl}}/cart/{{userId}}/{{productId}} HTTP/1.1
